{{- if or (.Values.keystone_patch_hook.enable) (.Values.rbac_ruleset_hook.enable) }}
{{- $context := . }}
{{- $saName := .Values.hook_service_account_name }}
{{- $releaseName := .Release.Name }}
{{- $saNamespace := .Release.Namespace }}
{{ tuple $context nil $saName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ $releaseName }}-{{ $saNamespace }}-{{ $saName }}
  namespace: {{ $saNamespace }}
rules:
  - apiGroups:
      - ""
    verbs:
      - get
      - list
    resources:
      - pods
  - apiGroups:
      - ""
    verbs:
      - create
    resources:
      - pods/exec
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ $releaseName }}-{{ $saName }}
  namespace: {{ $saNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $releaseName }}-{{ $saNamespace }}-{{ $saName }}
subjects:
  - kind: ServiceAccount
    name: {{ $saName }}
    namespace: {{ $saNamespace }}
{{- end }}
